version: "3.8"
services:
  web:
    build: .
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bracket
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"