

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
    - ../frontend/nginx.conf:/etc/nginx/nginx.conf

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=bracket.c7ykagzynji7.us-east-1.rds.amazonaws.com
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=bracket
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

