services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:80" # Change frontend port to 3000 to avoid conflict
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ../frontend/nginx.conf:/etc/nginx/nginx.conf

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:80" # Keep backend on 5000
    environment:
      - DATABASE_HOST=bracket.c7ykagzynji7.us-east-1.rds.amazonaws.com
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=VolleyballTournament
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
