version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    ports:
      - "8080:80"
    environment:
      - DATABASE_HOST=bracket.xxxxxxx.us-east-1.rds.amazonaws.com
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=bracket
    depends_on:
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
