AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ECSCluster:
    Type: "AWS::ECS::Cluster"
    Properties:
      ClusterName: "bracket-cluster"

  ECSService:
    Type: "AWS::ECS::Service"
    Properties:
      Cluster: !Ref ECSCluster
      DesiredCount: 2
      TaskDefinition: !Ref ECSTaskDefinition

  ECSTaskDefinition:
    Type: "AWS::ECS::TaskDefinition"
    Properties:
      Family: "bracket-app"
      NetworkMode: "awsvpc"
      ContainerDefinitions:
        - Name: "frontend"
          Image: "<your_docker_image>"
          Memory: 512
          PortMappings:
            - ContainerPort: 80
        - Name: "backend"
          Image: "<your_docker_image>"
          Memory: 512
          PortMappings:
            - ContainerPort: 8080