name: Deploy to ECS (Amazon Linux)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to ECS with Amazon Linux
        uses: aws-actions/amazon-ecs-deploy-action@v1
        with:
          cluster: your-cluster-name        # Replace with your ECS cluster name
          service: your-service-name        # Replace with your ECS service name
          task-definition: your-task-def   # Replace with your ECS task definition
          desired-count: 1                 # Number of tasks
