name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger action on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bracket:latest .

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker Image to Amazon ECR
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/bracket:latest ${{ secrets.ECR_REPO_URL }}:latest
          docker push ${{ secrets.ECR_REPO_URL }}:latest

      - name: Deploy to ECS (optional)
        run: |
          # Add ECS deploy commands here, if needed
          echo "Deploying to ECS..."
